// ============================================================================
// register_events.js  —  Event registration helper
// ============================================================================
//
// HOW TO USE
// ----------
//
// 1. Import the helper next to your other openlcb imports:
//
//      import { OpenLcb } from 'openlcb-js-lib';
//      import { NODE_ID, OpenLcbUserConfig_node_parameters }
//          from './openlcb_user_config.js';
//      import { registerEvents } from './register_events.js';
//
// 2. Call registerEvents() once after creating your node:
//
//      const lib  = await OpenLcb.create({ /* transport options */ });
//      const node = lib.createNode(NODE_ID, OpenLcbUserConfig_node_parameters);
//      registerEvents(node);
//
// 3. After this returns, the node is registered as producer / consumer of
//    every Well Known Event you selected in the Node Wizard, plus any
//    protocol-required defaults for the chosen node type.
//
// Generated by Node Wizard — Copyright (c) 2026, Jim Kueneman
// <YOUR LICENSE TEXT HERE>

import { Event, EventStatus, EventRangeCount } from '../../src/openlcb/constants.js';

export function registerEvents(node) {

    // -------------------------------------------------------------------
    // Producers
    // -------------------------------------------------------------------

    // Throttle produces emergency events to stop/resume all trains
    node.registerProducer(Event.EMERGENCY_STOP,       EventStatus.EVENT_STATUS_UNKNOWN);
    node.registerProducer(Event.CLEAR_EMERGENCY_STOP, EventStatus.EVENT_STATUS_UNKNOWN);
    node.registerProducer(Event.EMERGENCY_OFF,        EventStatus.EVENT_STATUS_UNKNOWN);
    node.registerProducer(Event.CLEAR_EMERGENCY_OFF,  EventStatus.EVENT_STATUS_UNKNOWN);

    // Well Known Event producers (selected in Node Wizard)

    // -------------------------------------------------------------------
    // Consumers
    // -------------------------------------------------------------------

    // Throttle consumes "Is Train" so it can discover trains on the bus
    node.registerConsumer(Event.IS_TRAIN, EventStatus.EVENT_STATUS_UNKNOWN);

}
